//! Matchmaking system output validation.

use std::fmt::Display;
use std::time::Duration;

use serde::{Deserialize, Serialize};

use crate::generator::generator::MatchmakingRequest;
use crate::matchmaking::utils::now;

/// Matchmaking assignments generated by the matchmaker.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchmakingAssignment {
    pub grouped_requests: Vec<MatchmakingRequest>,
}

/// Matchmaking assignment validator. Computes metrics that are
/// pointwise-distributive over collections of assignments.
pub struct MatchmakingAssignmentValidator {
    filled_request_count: usize,
    assignment_count: usize,
    total_metric_score: f64,
    total_response_time: f64,
}

/// Matchmaker evaluation metrics.
#[derive(Debug, Clone, Copy)]
pub struct MatchmakerMetrics {
    pub rating_variability_average_penalty: f64,
    pub mean_response_time: f64,
    pub evaluated_timestamp: Duration,
}

impl Display for MatchmakerMetrics {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl MatchmakingAssignmentValidator {
    /// Constructs a new matchmaking assignment validator.
    pub fn new() -> MatchmakingAssignmentValidator {
        MatchmakingAssignmentValidator {
            filled_request_count: 0,
            assignment_count: 0,
            total_metric_score: 0.0,
            total_response_time: 0.0,
        }
    }

    /// Receives a new completed assignment.
    pub fn receive(&mut self, assignment: MatchmakingAssignment) {
        let received_timestamp = now();

        self.filled_request_count += assignment.grouped_requests.len();
        self.assignment_count += 1;
        self.total_metric_score += Self::compute_rating_variability_penalty(&assignment);
        self.total_response_time +=
            Self::compute_total_response_time(&assignment, &received_timestamp);
    }

    /// Evaluates the matchmaker's current performance as of all received
    /// assignments.
    pub fn evaluate_performance(&self) -> MatchmakerMetrics {
        if self.filled_request_count == 0 {
            return MatchmakerMetrics {
                rating_variability_average_penalty: 0.0,
                mean_response_time: 0.0,
                evaluated_timestamp: now(),
            };
        }

        MatchmakerMetrics {
            rating_variability_average_penalty: self.total_metric_score
                / self.assignment_count as f64,
            mean_response_time: self.total_response_time / self.filled_request_count as f64,
            evaluated_timestamp: now(),
        }
    }

    /// Extracts ratings from all grouped players in an assignment.
    fn extract_ratings(assignment: &MatchmakingAssignment) -> Vec<u32> {
        let mut result = Vec::with_capacity(assignment.grouped_requests.len());

        for &MatchmakingRequest { skill_rating, .. } in assignment.grouped_requests.iter() {
            result.push(skill_rating);
        }

        result
    }

    /// Computes the rating variability penalty metric for an assignment.
    fn compute_rating_variability_penalty(assignment: &MatchmakingAssignment) -> f64 {
        const ALPHA: f64 = 1.0;
        const BETA: f64 = 1.0;
        const GAMMA: i32 = 2;

        let ratings = MatchmakingAssignmentValidator::extract_ratings(assignment);
        let count = assignment.grouped_requests.len();

        debug_assert!(count > 0);

        let mean = ratings.iter().sum::<u32>() as f64 / count as f64;
        let max = ratings.iter().max().unwrap().to_owned();
        let min = ratings.iter().min().unwrap().to_owned();
        let variance: f64 = ratings
            .iter()
            .map(|&r| (r as f64 - mean).powi(2))
            .sum::<f64>()
            / count as f64;

        ALPHA * variance + BETA * ((max - min) as f64).powi(GAMMA)
    }

    /// Computes the total response time for all fulfilled requests in an
    /// assignment.
    fn compute_total_response_time(
        assignment: &MatchmakingAssignment,
        reception_time: &Duration,
    ) -> f64 {
        let mut result = 0.0;

        for MatchmakingRequest {
            submission_timestamp,
            ..
        } in assignment.grouped_requests.iter()
        {
            result += reception_time
                .checked_sub(*submission_timestamp)
                .unwrap()
                .as_secs_f64();
        }

        result
    }
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use super::*;

    const ASSIGNMENT_SIZE: usize = 10;

    fn assignment_from_ratings(
        ratings: [u32; ASSIGNMENT_SIZE],
        submission_timestamp: Duration,
    ) -> MatchmakingAssignment {
        MatchmakingAssignment {
            grouped_requests: (0..ASSIGNMENT_SIZE)
                .map(|index| MatchmakingRequest {
                    request_id: index as u32,
                    skill_rating: ratings[index],
                    submission_timestamp,
                })
                .collect(),
        }
    }

    #[test]
    fn rating_variability_penalty_is_zero_for_uniform_ratings() {
        let assignment = assignment_from_ratings([1000; ASSIGNMENT_SIZE], Duration::ZERO);

        let penalty =
            MatchmakingAssignmentValidator::compute_rating_variability_penalty(&assignment);

        assert_eq!(penalty, 0.0);
    }

    #[test]
    fn rating_variability_penalty_matches_variance_plus_squared_range() {
        let assignment = assignment_from_ratings([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], Duration::ZERO);

        let penalty =
            MatchmakingAssignmentValidator::compute_rating_variability_penalty(&assignment);

        let expected_variance = 8.25;
        let expected_range_squared = 81.0;

        assert!(
            (penalty - (expected_variance + expected_range_squared)).abs() < f64::EPSILON,
            "expected penalty {}, got {}",
            expected_variance + expected_range_squared,
            penalty
        );
    }

    #[test]
    fn total_response_time_sums_request_wait_times() {
        let reception_time = Duration::from_secs(1_000);
        let assignment = MatchmakingAssignment {
            grouped_requests: (0..ASSIGNMENT_SIZE)
                .map(|index| MatchmakingRequest {
                    request_id: index as u32,
                    skill_rating: 1000,
                    submission_timestamp: reception_time
                        .checked_sub(Duration::from_secs((index + 1) as u64))
                        .unwrap(),
                })
                .collect(),
        };

        let total_response_time = MatchmakingAssignmentValidator::compute_total_response_time(
            &assignment,
            &reception_time,
        );

        assert!((total_response_time - 55.0).abs() < f64::EPSILON);
    }

    #[test]
    fn evaluate_performance_of_empty_validator_returns_zero_metrics() {
        let validator = MatchmakingAssignmentValidator::new();

        let metrics = validator.evaluate_performance();

        assert_eq!(metrics.rating_variability_average_penalty, 0.0);
        assert_eq!(metrics.mean_response_time, 0.0);
    }

    #[test]
    fn receive_accumulates_metrics_across_calls() {
        let mut validator = MatchmakingAssignmentValidator::new();

        let assignment_a = assignment_from_ratings([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], Duration::ZERO);
        let assignment_b = assignment_from_ratings(
            [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
            Duration::from_secs(100),
        );

        validator.receive(assignment_a);
        validator.receive(assignment_b);

        let metrics = validator.evaluate_performance();
        // two assignments with different rating spreads → non-zero penalty average
        assert!(metrics.rating_variability_average_penalty > 0.0);
    }

    #[test]
    fn evaluate_performance_after_one_receive() {
        let mut validator = MatchmakingAssignmentValidator::new();

        validator.receive(assignment_from_ratings(
            [1000; ASSIGNMENT_SIZE],
            Duration::ZERO,
        ));

        let metrics = validator.evaluate_performance();
        assert_eq!(metrics.rating_variability_average_penalty, 0.0);
        // response_time depends on now() minus submission — not checked here
    }

    #[test]
    fn evaluate_performance_averages_across_multiple_assignments() {
        let mut validator = MatchmakingAssignmentValidator::new();

        validator.receive(assignment_from_ratings(
            [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
            Duration::ZERO,
        ));
        validator.receive(assignment_from_ratings(
            [1000; ASSIGNMENT_SIZE],
            Duration::ZERO,
        ));

        let metrics = validator.evaluate_performance();
        // two assignments: one with non-zero penalty, one zero → average > 0
        assert!(metrics.rating_variability_average_penalty > 0.0);
    }
}
